"""
evaluate.py

RAG evaluation pipeline for the UiA IKT course chatbot.

Generator : phi4:14b     (Ollama, GPU) — strong instruction following
Judge     : qwen2.5:7b   (Ollama, GPU) — reliable structured JSON output

Expected answers are loaded from expected_answers.csv (generated by
generate_expected_answers.py).  The relevance judge compares the RAG
answer against the reference answer, making scoring much more reliable
than judging against the question alone.

Requires:
    Ollama running with phi4:14b and qwen2.5:7b pulled (uses GPU automatically)
"""

import csv
import datetime
import json
import re
import time
from pathlib import Path
from typing import Optional

import pandas as pd
import psutil
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_ollama import ChatOllama
from tqdm import tqdm

OLLAMA_BASE_URL = "http://localhost:11434"
CHROMA_DIR = "./chroma_langchain_db"
EXPECTED_ANSWERS_PATH = "./expected_answers.csv"
RESULTS_PATH = "./experiment_results.csv"
SUMMARY_PATH = "./experiment_results_summary.csv"

# ─── Experiment config (must match the indexed collection) ────────────────────
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
CHUNK_SIZE = 500
CHUNK_OVERLAP = 100
K = 10
GENERATOR_MODEL = "phi4:14b"
JUDGE_MODEL = "qwen2.5:7b"

COURSE_CODE_RE = re.compile(r"\bIKT\d{3}\b")

# ─── Models ───────────────────────────────────────────────────────────────────

generator_llm = ChatOllama(
    model=GENERATOR_MODEL,
    temperature=0,
    base_url=OLLAMA_BASE_URL,
    num_predict=2048,  # synthesis answers can be long
)

judge_llm = ChatOllama(
    model=JUDGE_MODEL,
    temperature=0,
    base_url=OLLAMA_BASE_URL,
    num_predict=512,
)

# ─── Retrieval ────────────────────────────────────────────────────────────────

embeddings = HuggingFaceEmbeddings(
    model_name=EMBEDDING_MODEL,
    model_kwargs={"device": "cpu"},
    encode_kwargs={"normalize_embeddings": True},
)

vectorstore = Chroma(
    persist_directory=CHROMA_DIR,
    collection_name="uia_courses",
    embedding_function=embeddings,
)

retriever = vectorstore.as_retriever(search_kwargs={"k": K})

print(f"RAG system loaded (generator: {GENERATOR_MODEL}, judge: {JUDGE_MODEL})")


def augmented_retrieve(question: str) -> list:
    """Semantic top-k + guaranteed coverage for named course codes."""
    docs = retriever.invoke(question)
    seen = {d.page_content[:80] for d in docs}
    for code in set(COURSE_CODE_RE.findall(question.upper())):
        for doc in vectorstore.similarity_search(code, k=3):
            key = doc.page_content[:80]
            if key not in seen:
                docs.append(doc)
                seen.add(key)
    return docs

# ─── Prompts ──────────────────────────────────────────────────────────────────

RAG_PROMPT = """\
You are a course information assistant for UiA (University of Agder).
Answer using ONLY the information provided in the context below. Do not use prior knowledge about any courses.

Rules:
- If the information is not in the context, say exactly: "The information is not provided in the retrieved context."
- Factual questions (ECTS credits, instructor, language, semester): give a brief, direct answer.
- Comparison questions: address each course mentioned in the question separately and systematically.
- List or synthesis questions: enumerate every matching item found in the context; do not assume there are more beyond what the context shows.
- Never infer or guess anything not explicitly stated.

Context:
{context}

Question: {question}

Answer:"""

GROUNDING_PROMPT = """\
You are evaluating a RAG system answer for factual grounding.

Question:
{question}

Retrieved Context:
{context}

Generated Answer:
{answer}

Task: Is every claim in the answer directly supported by the retrieved context?

Return ONLY valid JSON with no markdown:
{{
  "score": <float 0.0–1.0>,
  "verdict": "<pass|fail>",
  "unsupported_claims": [<list of strings>],
  "reason": "<one sentence>"
}}

Scoring:
- 1.0 = every claim is explicitly present in the context
- 0.0 = answer is entirely unsupported or hallucinated
- Be strict: inferences not stated in the context count as unsupported
- A correct "I don't know" answer when the context lacks the information is fully grounded (1.0)"""

RELEVANCE_PROMPT = """\
You are evaluating whether a RAG-generated answer matches the reference answer for a given question.

Question:
{question}

Reference Answer (gold standard):
{expected_answer}

Generated Answer:
{answer}

Task: How well does the generated answer cover the key facts in the reference answer?

Return ONLY valid JSON with no markdown:
{{
  "score": <float 0.0–1.0>,
  "verdict": "<pass|fail>",
  "missing_points": [<list of strings>],
  "reason": "<one sentence>"
}}

Scoring:
- 1.0 = all key facts from the reference are present and correct
- 0.5 = partial coverage, some key facts missing or imprecise
- 0.0 = completely wrong or irrelevant
- Minor wording differences are fine; missing key facts are penalized
- "pass" if score >= 0.7, else "fail"
- If the reference says information is not available and the generated answer says the same, score 1.0"""

# ─── Helpers ──────────────────────────────────────────────────────────────────

def safe_parse_json(text: str) -> dict | None:
    # Strip markdown code fences (```json ... ``` or ``` ... ```)
    text = re.sub(r"```(?:json)?\s*", "", text).strip()
    try:
        return json.loads(text)
    except Exception:
        pass
    try:
        start = text.find("{")
        end = text.rfind("}") + 1
        if start != -1 and end > start:
            return json.loads(text[start:end])
    except Exception:
        pass
    return None


def normalize_score(value) -> float:
    try:
        v = float(value)
    except Exception:
        return 0.0
    return max(0.0, min(1.0, v))


def clean_text(text) -> str:
    if text is None:
        return ""
    return str(text).replace("\r", " ").replace("\n", " \\n ").strip()


def run_grounding_judge(question: str, context: str, answer: str) -> dict:
    prompt = GROUNDING_PROMPT.format(question=question, context=context, answer=answer)
    parsed = safe_parse_json(judge_llm.invoke(prompt).content)
    if parsed is not None:
        parsed["score"] = normalize_score(parsed.get("score", 0.0))
        return parsed
    return {"score": 0.0, "verdict": "fail", "reason": "Invalid JSON from judge", "unsupported_claims": []}


def run_relevance_judge(question: str, expected_answer: str, answer: str) -> dict:
    prompt = RELEVANCE_PROMPT.format(
        question=question,
        expected_answer=expected_answer,
        answer=answer,
    )
    parsed = safe_parse_json(judge_llm.invoke(prompt).content)
    if parsed is not None:
        parsed["score"] = normalize_score(parsed.get("score", 0.0))
        return parsed
    return {"score": 0.0, "verdict": "fail", "reason": "Invalid JSON from judge", "missing_points": []}

# ─── Energy / CPU helpers ─────────────────────────────────────────────────────

RAPL_ENERGY_PATH = "/sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj"
RAPL_MAX_PATH    = "/sys/class/powercap/intel-rapl/intel-rapl:0/max_energy_range_uj"


def _read_rapl_uj() -> Optional[float]:
    try:
        return float(Path(RAPL_ENERGY_PATH).read_text().strip())
    except Exception:
        return None


def _energy_delta_j(start_uj: Optional[float], end_uj: Optional[float]) -> Optional[float]:
    if start_uj is None or end_uj is None:
        return None
    delta = end_uj - start_uj
    if delta < 0:
        try:
            delta += float(Path(RAPL_MAX_PATH).read_text().strip())
        except Exception:
            return None
    return round(delta / 1_000_000, 4)


def _cpu_time_s() -> float:
    t = psutil.Process().cpu_times()
    return t.user + t.system


def _next_exp_id(summary_path: str) -> str:
    p = Path(summary_path)
    if not p.exists():
        return "exp000"
    try:
        df = pd.read_csv(p)
        return f"exp{len(df):03d}"
    except Exception:
        return "exp000"


# ─── Question set ─────────────────────────────────────────────────────────────

QUESTION_SET = [
    {"id": "q001", "question": "Which course is taught by Morten Goodwin?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT469"], "evidence_fields": ["course_leader", "title"]},
    {"id": "q002", "question": "How many ECTS credits is IKT469 Deep Neural Networks worth?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT469"], "evidence_fields": ["title", "ects_credits"]},
    {"id": "q003", "question": "What is the teaching language of IKT112 Concepts of Machine Learning?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT112"], "evidence_fields": ["title", "teaching_language"]},
    {"id": "q004", "question": "Who is the course leader for IKT204 Data communication?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT204"], "evidence_fields": ["title", "course_leader"]},
    {"id": "q005", "question": "In which semester is IKT443 WiFi and Internet of Things offered?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT443"], "evidence_fields": ["title", "lecture_semester"]},
    {"id": "q006", "question": "Is IKT115 Introduction to Artificial Intelligence Technology offered as a free-standing course?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT115"], "evidence_fields": ["title", "offered_as_a_free_standing_course"]},
    {"id": "q007", "question": "What is the duration of IKT302 Bachelor's Thesis, data?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT302"], "evidence_fields": ["title", "duration"]},
    {"id": "q008", "question": "Which course is led by Andreas Prinz?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT122"], "evidence_fields": ["course_leader", "title"]},
    {"id": "q009", "question": "What are the examination components for IKT112 Concepts of Machine Learning?", "answer_type": "descriptive", "difficulty": "medium", "course_scope": ["IKT112"], "evidence_fields": ["title", "examinations"]},
    {"id": "q010", "question": "Summarize the main learning outcomes of IKT469 Deep Neural Networks.", "answer_type": "summary", "difficulty": "medium", "course_scope": ["IKT469"], "evidence_fields": ["title", "learning_outcomes"]},
    {"id": "q011", "question": "What teaching and learning methods are used in IKT460 Reinforcement Learning?", "answer_type": "descriptive", "difficulty": "medium", "course_scope": ["IKT460"], "evidence_fields": ["title", "teaching_and_learning_methods"]},
    {"id": "q012", "question": "What are the admission requirements and recommended previous knowledge for IKT204 Data communication?", "answer_type": "descriptive", "difficulty": "medium", "course_scope": ["IKT204"], "evidence_fields": ["title", "admission_requirement_if_given_as_a_free_standing_course", "recommended_previous_knowledge"]},
    {"id": "q013", "question": "What are the prerequisites for starting IKT302 Bachelor's Thesis, data?", "answer_type": "descriptive", "difficulty": "medium", "course_scope": ["IKT302"], "evidence_fields": ["title", "prerequisites"]},
    {"id": "q014", "question": "What are the compulsory requirements for IKT590 Master's Thesis?", "answer_type": "descriptive", "difficulty": "medium", "course_scope": ["IKT590"], "evidence_fields": ["title", "examination_requirements"]},
    {"id": "q015", "question": "Compare the assessment methods of IKT469 Deep Neural Networks and IKT468 Applied Algorithms.", "answer_type": "comparison", "difficulty": "medium", "course_scope": ["IKT469", "IKT468"], "evidence_fields": ["title", "examinations"]},
    {"id": "q016", "question": "Which has more ECTS credits: IKT112 Concepts of Machine Learning or IKT215 Pattern Recognition?", "answer_type": "comparison", "difficulty": "easy", "course_scope": ["IKT112", "IKT215"], "evidence_fields": ["title", "ects_credits"]},
    {"id": "q017", "question": "Compare the workload of IKT112, IKT215, and IKT469.", "answer_type": "comparison", "difficulty": "medium", "course_scope": ["IKT112", "IKT215", "IKT469"], "evidence_fields": ["title", "teaching_and_learning_methods"]},
    {"id": "q018", "question": "Which course has a larger exam component: IKT112 Concepts of Machine Learning or IKT443 WiFi and Internet of Things?", "answer_type": "comparison", "difficulty": "medium", "course_scope": ["IKT112", "IKT443"], "evidence_fields": ["title", "examinations"]},
    {"id": "q019", "question": "Compare IKT452 Computer Vision and IKT460 Reinforcement Learning in terms of course content focus.", "answer_type": "comparison", "difficulty": "medium", "course_scope": ["IKT452", "IKT460"], "evidence_fields": ["title", "contents"]},
    {"id": "q020", "question": "Which course is most directly focused on deep learning and retrieval-augmented systems?", "answer_type": "recommendation", "difficulty": "medium", "course_scope": ["IKT469"], "evidence_fields": ["title", "learning_outcomes", "contents"]},
    {"id": "q021", "question": "Which course would best fit a student who wants to learn reinforcement learning specifically?", "answer_type": "recommendation", "difficulty": "easy", "course_scope": ["IKT460"], "evidence_fields": ["title", "contents", "learning_outcomes"]},
    {"id": "q022", "question": "Which course is the best match for learning computer vision with hands-on implementation?", "answer_type": "recommendation", "difficulty": "medium", "course_scope": ["IKT452"], "evidence_fields": ["title", "contents", "learning_outcomes"]},
    {"id": "q023", "question": "Which courses appear most relevant for a student interested in IoT networking and communication technologies?", "answer_type": "synthesis", "difficulty": "hard", "course_scope": ["IKT443", "IKT458", "IKT520", "IKT204"], "evidence_fields": ["title", "contents", "learning_outcomes"]},
    {"id": "q024", "question": "If a student wants a course on intelligent data processing and large-scale data-driven decision making, which course fits best?", "answer_type": "recommendation", "difficulty": "easy", "course_scope": ["IKT453"], "evidence_fields": ["title", "contents", "learning_outcomes"]},
    {"id": "q025", "question": "Can a student take IKT204 Data communication as a free-standing course?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT204"], "evidence_fields": ["title", "offered_as_a_free_standing_course"]},
    {"id": "q026", "question": "What must students complete before they can take the exam in IKT443 WiFi and Internet of Things?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT443"], "evidence_fields": ["title", "examination_requirements"]},
    {"id": "q027", "question": "What prior knowledge is recommended for IKT452 Computer Vision?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT452"], "evidence_fields": ["title", "recommended_previous_knowledge"]},
    {"id": "q028", "question": "What prior knowledge is recommended for IKT519 Blockchain and distributed ledger technology?", "answer_type": "factoid", "difficulty": "easy", "course_scope": ["IKT519"], "evidence_fields": ["title", "admission_requirement_if_given_as_a_free_standing_course", "recommended_previous_knowledge"]},
    {"id": "q029", "question": "What are the minimum requirements to start IKT590 Master's Thesis?", "answer_type": "descriptive", "difficulty": "medium", "course_scope": ["IKT590"], "evidence_fields": ["title", "prerequisites"]},
    {"id": "q030", "question": "Who is the course leader for IKT433 Distributed and Big Data Systems?", "answer_type": "unanswerable", "difficulty": "easy", "course_scope": ["IKT433"], "evidence_fields": ["title", "course_leader"], "is_unanswerable": True},
    {"id": "q031", "question": "What is the exact duration of IKT433 Distributed and Big Data Systems?", "answer_type": "unanswerable", "difficulty": "easy", "course_scope": ["IKT433"], "evidence_fields": ["title", "duration"], "is_unanswerable": True},
    {"id": "q032", "question": "Which textbook is required for IKT469 Deep Neural Networks?", "answer_type": "unanswerable", "difficulty": "easy", "course_scope": ["IKT469"], "evidence_fields": ["title"], "is_unanswerable": True},
    {"id": "q033", "question": "On which weekday are lectures for IKT460 held?", "answer_type": "unanswerable", "difficulty": "easy", "course_scope": ["IKT460"], "evidence_fields": ["title"], "is_unanswerable": True},
    {"id": "q034", "question": "What is the classroom number for IKT122?", "answer_type": "unanswerable", "difficulty": "easy", "course_scope": ["IKT122"], "evidence_fields": ["title"], "is_unanswerable": True},
    {"id": "q035", "question": "Which spring 2026 courses in the dataset explicitly mention machine learning in either the title, learning outcomes, or contents?", "answer_type": "synthesis", "difficulty": "hard", "course_scope": ["IKT112", "IKT115", "IKT215", "IKT459", "IKT469", "IKT460"], "evidence_fields": ["title", "learning_outcomes", "contents"]},
    {"id": "q036", "question": "Which courses in the dataset are 30 ECTS thesis courses?", "answer_type": "list", "difficulty": "easy", "course_scope": ["IKT302", "IKT523", "IKT590"], "evidence_fields": ["title", "ects_credits"]},
    {"id": "q037", "question": "Which courses are taught in English and are available as free-standing courses, subject to availability?", "answer_type": "synthesis", "difficulty": "hard", "course_scope": ["multiple"], "evidence_fields": ["title", "teaching_language", "offered_as_a_free_standing_course"]},
    {"id": "q038", "question": "Which courses explicitly require compulsory assignments or exercises to be approved before examination?", "answer_type": "synthesis", "difficulty": "hard", "course_scope": ["IKT204", "IKT433", "IKT443", "IKT449", "IKT519", "IKT520"], "evidence_fields": ["title", "examination_requirements"]},
    {"id": "q039", "question": "Which courses appear most relevant for a student interested in cybersecurity?", "answer_type": "synthesis", "difficulty": "hard", "course_scope": ["IKT449", "IKT519", "IKT520", "IKT523", "IKT204"], "evidence_fields": ["title", "contents", "learning_outcomes"]},
    {"id": "q040", "question": "Which course best matches a student wanting to build multimodal and retrieval-augmented systems using embeddings and external knowledge?", "answer_type": "recommendation", "difficulty": "medium", "course_scope": ["IKT469"], "evidence_fields": ["title", "learning_outcomes", "contents"]},
]

# ─── Load expected answers ────────────────────────────────────────────────────

def load_expected_answers(path: str) -> dict:
    """Returns {question_id: expected_answer}."""
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(
            f"{path} not found. Run generate_expected_answers.py first."
        )
    df = pd.read_csv(path)
    if "question_id" in df.columns:
        return dict(zip(df["question_id"].astype(str), df["expected_answer"].astype(str)))
    # Fall back to matching by question text
    q_to_id = {item["question"]: item["id"] for item in QUESTION_SET}
    return {
        q_to_id[row["question"]]: row["expected_answer"]
        for _, row in df.iterrows()
        if row["question"] in q_to_id
    }


# ─── Evaluation loop ──────────────────────────────────────────────────────────

expected_answers = load_expected_answers(EXPECTED_ANSWERS_PATH)

exp_id = _next_exp_id(SUMMARY_PATH)
timestamp = datetime.datetime.now().isoformat()

exp_meta = {
    "exp_id": exp_id,
    "embedding_model": EMBEDDING_MODEL,
    "chunk_size": CHUNK_SIZE,
    "chunk_overlap": CHUNK_OVERLAP,
    "k": K,
    "generator_model": GENERATOR_MODEL,
    "judge_model": JUDGE_MODEL,
    "timestamp": timestamp,
}

rows = []
exp_start_wall = time.time()
exp_start_energy_uj = _read_rapl_uj()
exp_start_cpu_s = _cpu_time_s()

for item in tqdm(QUESTION_SET, desc=f"Evaluating RAG [{exp_id}]"):
    qid = item["id"]
    q = item["question"]
    expected = expected_answers.get(qid, "")

    docs = augmented_retrieve(q)
    raw_context = "\n\n".join(doc.page_content for doc in docs)

    q_start_energy_uj = _read_rapl_uj()
    q_start_cpu_s = _cpu_time_s()

    t0 = time.time()
    raw_answer = generator_llm.invoke(RAG_PROMPT.format(context=raw_context, question=q)).content.strip()
    gen_latency = round(time.time() - t0, 2)

    t1 = time.time()
    grounding = run_grounding_judge(q, raw_context, raw_answer)
    relevance = run_relevance_judge(q, expected, raw_answer)
    judge_latency = round(time.time() - t1, 2)

    rows.append({
        **exp_meta,
        "id": qid,
        "question": q,
        "expected_answer": expected,
        "answer_type": item["answer_type"],
        "difficulty": item["difficulty"],
        "course_scope": ", ".join(item["course_scope"]) if isinstance(item.get("course_scope"), list) else str(item.get("course_scope", "")),
        "evidence_fields": ", ".join(item.get("evidence_fields", [])),
        "is_unanswerable": item.get("is_unanswerable", False),
        "retrieved_docs": len(docs),
        "context": clean_text(raw_context),
        "answer": clean_text(raw_answer),
        "generation_latency_s": gen_latency,
        "judge_latency_s": judge_latency,
        "total_latency_s": round(gen_latency + judge_latency, 2),
        "cpu_time_s": round(_cpu_time_s() - q_start_cpu_s, 3),
        "energy_j": _energy_delta_j(q_start_energy_uj, _read_rapl_uj()),
        "grounding_score": grounding.get("score", 0.0),
        "grounding_verdict": grounding.get("verdict", ""),
        "grounding_reason": clean_text(grounding.get("reason", "")),
        "unsupported_claims": json.dumps(grounding.get("unsupported_claims", []), ensure_ascii=False),
        "relevance_score": relevance.get("score", 0.0),
        "relevance_verdict": relevance.get("verdict", ""),
        "relevance_reason": clean_text(relevance.get("reason", "")),
        "missing_points": json.dumps(relevance.get("missing_points", []), ensure_ascii=False),
    })

# ─── Save results ─────────────────────────────────────────────────────────────

exp_duration_s = round(time.time() - exp_start_wall, 2)
exp_energy_j = _energy_delta_j(exp_start_energy_uj, _read_rapl_uj())
exp_cpu_time_s = round(_cpu_time_s() - exp_start_cpu_s, 3)
n = len(rows)

grounding_passes = sum(1 for r in rows if r["grounding_verdict"] == "pass")
grounding_fails  = sum(1 for r in rows if r["grounding_verdict"] == "fail")
relevance_passes = sum(1 for r in rows if r["relevance_verdict"] == "pass")
relevance_fails  = sum(1 for r in rows if r["relevance_verdict"] == "fail")

summary_row = {
    **exp_meta,
    "total_questions": n,
    "experiment_duration_s": exp_duration_s,
    "total_cpu_time_s": exp_cpu_time_s,
    "total_energy_j": exp_energy_j,
    "mean_latency_per_question_s": round(sum(r["total_latency_s"] for r in rows) / n, 2),
    "mean_cpu_time_per_question_s": round(exp_cpu_time_s / n, 3),
    "mean_energy_per_question_j": round(exp_energy_j / n, 4) if exp_energy_j is not None else None,
    "grounding_passes": grounding_passes,
    "grounding_fails": grounding_fails,
    "relevance_passes": relevance_passes,
    "relevance_fails": relevance_fails,
    "mean_grounding_score": round(sum(r["grounding_score"] for r in rows) / n, 3),
    "mean_relevance_score": round(sum(r["relevance_score"] for r in rows) / n, 3),
}

def _append_csv(data: list[dict], path: str) -> None:
    df = pd.DataFrame(data)
    write_header = not Path(path).exists()
    df.to_csv(path, mode="a", index=False, header=write_header, quoting=csv.QUOTE_ALL)

_append_csv(rows, RESULTS_PATH)
_append_csv([summary_row], SUMMARY_PATH)

print(f"\nResults appended to {RESULTS_PATH}")
print(f"Summary appended to  {SUMMARY_PATH}")
print(f"\n{'─'*60}")
print(f"exp_id     : {exp_id}")
print(f"Grounding  — mean: {summary_row['mean_grounding_score']:.3f}  passes: {grounding_passes}/{n}")
print(f"Relevance  — mean: {summary_row['mean_relevance_score']:.3f}  passes: {relevance_passes}/{n}")
print(f"Duration   : {exp_duration_s}s")
print(f"{'─'*60}")
